spring:
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations:  classpath:db/migrations
    enabled: true
    mixed: true
    outOfOrder: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa

springdoc:
  swagger-ui:
    path=/swagger-ui.html:
validations:
  min-battery-level: 25
  batery:
    min: 25
